"""
Django settings for student_reg project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Default True for local dev; set DJANGO_DEBUG=false in production.
DEBUG = os.environ.get("DJANGO_DEBUG", "true").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    # Allow running locally without env vars; for any non-debug deployment,
    # you must set DJANGO_SECRET_KEY.
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        "localhost,127.0.0.1,quizapp-s39c.onrender.com"
    ).split(",")
    if h.strip()
]





CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        "https://quizapp-s39c.onrender.com"
    ).split(",")
    if o.strip()
]

# HTTPS origins for CSRF when behind a reverse proxy (comma-separated full URLs).
# Example: https://quiz.example.com,https://www.quiz.example.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if o.strip()
]

# Used for login throttling and one-shot quiz submission locks (use Redis/Memcached in production).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "quizapp",
    }
}

# Cookie/session security (safe defaults even for local HTTP)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Safe defaults in all environments (extra headers are ignored over plain HTTP).
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# Enable stronger transport security only when not debugging.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    CSRF_USE_SESSIONS = True

# Mitigate clickjacking (Django default is SAMEORIGIN; DENY is stricter for this app).
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app1.context_processors.student_profile',
            ],
        },
    },
]

LOGIN_URL = "/student/login/"
ADMIN_LOGIN_URL = "/admin/login/"

# Django built-in admin is disabled in urls.py; this path is kept for staff_member_required fallbacks.
ADMIN_URL = os.environ.get("DJANGO_INTERNAL_ADMIN_PATH", "").strip()


ROOT_URLCONF = 'Quiz_app.urls'
WSGI_APPLICATION = 'Quiz_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Seconds allowed per quiz question (enforced server-side in session).
QUIZ_QUESTION_SECONDS = int(os.environ.get("QUIZ_QUESTION_SECONDS", "60"))

# LNCTU AccSoft college ERP authentication (student login verification).
COLLEGE_LOGIN_URL = os.environ.get(
    "COLLEGE_LOGIN_URL",
    "https://accsoft.lnctu.ac.in/AccSoft2/StudentLogin.aspx",
).strip()
COLLEGE_PORTAL_URL = os.environ.get(
    "COLLEGE_PORTAL_URL",
    "https://accsoft.lnctu.ac.in/AccSoft2/Parents/ParentDesk1.aspx",
).strip()
COLLEGE_STUDENT_DETAILS_URL = os.environ.get(
    "COLLEGE_STUDENT_DETAILS_URL",
    "https://accsoft.lnctu.ac.in/AccSoft2/Parents/StudentPersonalDetails.aspx",
).strip()
_COLLEGE_BASE_URL = COLLEGE_LOGIN_URL.rsplit("/", 1)[0] + "/"
COLLEGE_PROFILE_URLS = [
    u.strip()
    for u in os.environ.get(
        "COLLEGE_PROFILE_URLS",
        ",".join(
            [
                COLLEGE_STUDENT_DETAILS_URL,
                COLLEGE_PORTAL_URL,
                f"{_COLLEGE_BASE_URL}Parents/ParentDesk1.aspx",
            ]
        ),
    ).split(",")
    if u.strip()
]
COLLEGE_SUCCESS_URL_MARKER = os.environ.get(
    "COLLEGE_SUCCESS_URL_MARKER",
    "ParentDesk",
).strip()
COLLEGE_AUTH_TIMEOUT = int(os.environ.get("COLLEGE_AUTH_TIMEOUT", "25"))

# OpenAI — optional; without a key, built-in sample questions are used for AI generate.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini").strip()

