"""
Django settings for student_reg project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured

# Load environment variables from .env file (dev convenience; in prod use real env vars).
from dotenv import load_dotenv
load_dotenv(Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Default True for local dev; set DJANGO_DEBUG=false in production.
# Accept DEBUG (preferred) or the legacy DJANGO_DEBUG for backward compatibility.
DEBUG = os.environ.get("DEBUG", os.environ.get("DJANGO_DEBUG", "true")).strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not SECRET_KEY:
    # Allow running locally without env vars; for any non-debug deployment,
    # you must set DJANGO_SECRET_KEY.
    if DEBUG:
        SECRET_KEY = "django-insecure-dev-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false.")

# Accept ALLOWED_HOSTS (preferred) or legacy DJANGO_ALLOWED_HOSTS.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "ALLOWED_HOSTS",
        os.environ.get(
            "DJANGO_ALLOWED_HOSTS",
            "localhost,127.0.0.1,quizapp-s39c.onrender.com",
        ),
    ).split(",")
    if h.strip()
]

# Public base URL of the app (used for building absolute callback/redirect URLs
# in production behind a proxy). Read from env; no secret value.
APP_BASE_URL = os.environ.get("APP_BASE_URL", "").strip().rstrip("/")





# HTTPS origins trusted for CSRF (full scheme+host, comma-separated).
# Behind a reverse proxy (e.g. Render), set DJANGO_CSRF_TRUSTED_ORIGINS to your
# public https URL(s), e.g. https://quiz.example.com,https://www.quiz.example.com
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        os.environ.get(
            "DJANGO_CSRF_TRUSTED_ORIGINS",
            "https://quizapp-s39c.onrender.com",
        ),
    ).split(",")
    if o.strip()
]

# Used for login throttling and one-shot quiz submission locks (use Redis/Memcached in production).
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "quizapp",
    }
}

# Cookie/session security (safe defaults even for local HTTP)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Limit session lifetime and re-expire on browser close for shared machines.
SESSION_COOKIE_AGE = int(os.environ.get("DJANGO_SESSION_COOKIE_AGE", str(60 * 60 * 8)))  # 8 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Cap request body / uploaded file sizes to blunt memory-exhaustion abuse.
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Safe defaults in all environments (extra headers are ignored over plain HTTP).
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# Enable stronger transport security only when not debugging.
if not DEBUG:
    # Behind a TLS-terminating reverse proxy (Render, Heroku, Nginx, etc.) Django
    # must trust the X-Forwarded-Proto header, otherwise request.is_secure() is
    # always False — breaking SSL redirect (loop) and secure-cookie enforcement.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
    CSRF_USE_SESSIONS = True

# Mitigate clickjacking (Django default is SAMEORIGIN; DENY is stricter for this app).
X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app1',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR,'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app1.context_processors.student_profile',
            ],
        },
    },
]

LOGIN_URL = "/student/login/"
ADMIN_LOGIN_URL = "/admin/login/"

# Django built-in admin is disabled in urls.py; this path is kept for staff_member_required fallbacks.
ADMIN_URL = os.environ.get("DJANGO_INTERNAL_ADMIN_PATH", "").strip()


ROOT_URLCONF = 'Quiz_app.urls'
WSGI_APPLICATION = 'Quiz_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Primary: Supabase PostgreSQL via DATABASE_URL (use the Supabase "Session
# Pooler" connection string). SSL is required and connections are reused.
# Fallback: local SQLite — ONLY when DEBUG is on AND DATABASE_URL is absent.
# Production (DEBUG=False) requires DATABASE_URL and fails clearly otherwise.
#
# DATABASE_URL is read from the environment only and is never logged/printed.
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=60,          # reuse connections for up to 60s
            conn_health_checks=True,  # verify a reused connection is alive
            ssl_require=True,         # Supabase requires TLS
        )
    }
elif DEBUG:
    # Local development convenience only. Never used when DEBUG is False.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    raise ImproperlyConfigured(
        "DATABASE_URL must be set in production (DEBUG=False). "
        "Provide the Supabase Session Pooler PostgreSQL connection string."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATICFILES_STORAGE = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Seconds allowed per quiz question (enforced server-side in session).
QUIZ_QUESTION_SECONDS = int(os.environ.get("QUIZ_QUESTION_SECONDS", "60"))

# OpenAI — optional; without a key, built-in sample questions are used for AI generate.
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-4o-mini").strip()



# ═══════════════════════════════════════════════════════════════
# Supabase Configuration (read from environment only — never hardcode keys)
# ═══════════════════════════════════════════════════════════════
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip()
SUPABASE_PUBLISHABLE_KEY = os.environ.get("SUPABASE_PUBLISHABLE_KEY", "").strip()
SUPABASE_SECRET_KEY = os.environ.get("SUPABASE_SECRET_KEY", "").strip()
