# Generated by Django 5.2 on 2025-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_category_question_option_quiz_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/'),
        ),
    ]
