# Generated by Django 5.1.6 on 2026-07-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_company_answer_is_correct_attempt_correct_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
